import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilepic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilepic} alt="" className="w-full h-auto" />
            </div>
            <div className="w-1/2">
              <h1>
                
              </h1>
              <AnimatedText text="Bringing Ideas to Life by Merging Coding Expertise with
                Innovative Design."/>
              <p>
                As a proficient full-stack developer, my passion lies in shaping
                ideas into captivating and forward-thinking web applications.
                Discover a showcase of my latest projects and articles,
                unveiling my mastery in React.js and the expansive field of web
                development.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
